# Generated by Django 5.2.4 on 2025-07-08 13:48

import api.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=api.models.create_api_key, max_length=128, unique=True)),
                ('name', models.CharField(help_text='Human-readable name for this API key', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Notes about this API key')),
                ('tokens_used', models.IntegerField(default=0)),
                ('tokens_limit', models.IntegerField(default=0)),
                ('token_limit_duration', models.DurationField(default=datetime.timedelta(days=30))),
                ('requests_sent', models.IntegerField(default=0)),
                ('rpm', models.IntegerField(default=0)),
                ('max_rpm', models.IntegerField(default=1000)),
                ('rpm_reset_at', models.DateTimeField(default=api.models.get_rpm_reset_time)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=256, unique=True)),
                ('provider', models.CharField(choices=[('ollama', 'ollama'), ('vllm', 'vllm'), ('groq', 'groq')], max_length=50)),
                ('cost_per_input_token', models.DecimalField(decimal_places=8, max_digits=10)),
                ('cost_per_output_token', models.DecimalField(decimal_places=8, max_digits=10)),
                ('device', models.CharField(max_length=100)),
                ('max_context_length', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('time_taken', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=6, max_digits=10)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apikey')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.llmmodel')),
            ],
        ),
    ]
