# Generated by Django 5.2.4 on 2025-07-08 13:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default=api.models.create_api_key, max_length=32, unique=True),
        ),
    ]
