# Generated by Django 5.2.4 on 2025-07-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apikey_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='token_limit_duration',
        ),
        migrations.AddField(
            model_name='apikey',
            name='token_limit_reset_days',
            field=models.IntegerField(default=30),
        ),
    ]
