# Generated by Django 5.2.4 on 2025-07-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_apikey_token_limit_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='token_limit_reset_days',
            new_name='tokens_usage_reset_duration_days',
        ),
    ]
